# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - uses: jpribyl/action-docker-layer-caching@v0.1.0
        continue-on-error: true
      - name: 'Docker Compose'
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build --force-recreate"
      - name: Save text_summary
        if: success()
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "text_summary:latest"
          retention_days: "30"
      - name: Save sentiment score
        if: success()
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "sentiment_score:latest"
          retention_days: "30"
      - name: Prepare logs folder
        run: |
          mkdir ./logs
          docker stats --no-stream
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz